# Example Google App Engine Deployment Configuration
runtime: nodejs18

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  
handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic 